POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Test Author",
  "url": "http://wwww.test.com",
  "title": "Blog Test Title"
}
######### WITH Auth
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlcmlrU2FuZCIsIm5hbWUiOiJFcmlrIFNhbmRzdHJvbSIsImlhdCI6MTY1NDExNjM0N30.rU0tbfwFiBQaWwaFVVa9szirsOAUW_EQnNxQkyUdAVM

{
  "author": "Auth Auth",
  "url": "http://wwww.auth.com",
  "title": "Different Blog by Auth Auth"
}
######### BAD QUERY
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Test Author"
}
######### BAD QUERY (1 missing value)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Test Author",
  "url": "www.google.com"
}
######## BAD QUERY (wrong data type)
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Test Author",
  "url": 00000,
  "title": "Blog Test Title"
}